### ISSUE TITLE
question: How do I set a handler for events of data_offer?

### ISSUE THREAD

**Issue by WhyNotHugo** [MaxVerevkin/wayrs#1]
When the server emits [`wl_data_device::Selection`](https://docs.rs/wayrs-client/0.8.0/wayrs_client/protocol/wl_data_device/enum.Event.html#variant.Selection), how do I set a callback for events coming from the `wl_data_offer` with the matching `ObjectId`?

**Comment by MaxVerevkin** [comment]
You can use [`Connection::set_callback_for`](https://docs.rs/wayrs-client/0.8.0/wayrs_client/connection/struct.Connection.html#method.set_callback_for). You probably want to set the callback right when you receive `wl_data_device::DataOffer`.

**Comment by WhyNotHugo** [comment]
Right, thanks!
