### ISSUE TITLE
Missing input-method-v1 protocol

### ISSUE THREAD

**Issue by eminfedar** [MaxVerevkin/wayrs#13]
Can I use this protocol with wayrs? As far as I checked, it is not included in lib.rs as a protocol:

https://wayland.app/protocols/input-method-unstable-v2

**Comment by MaxVerevkin** [comment]
You absolutely can, but you will have to have a local copy of the xml file and call `wayrs_client::generate!(<path>)`. Currently `wayrs-protocols` only provides protocols which are part of [wayland-protocols](https://gitlab.freedesktop.org/wayland/wayland-protocols/) or [wlr-protocols](https://gitlab.freedesktop.org/wlroots/wlr-protocols). `input-method-v2` is not part of either, for some reason.

**Comment by eminfedar** [comment]
@MaxVerevkin I also checked `input-method-unstable-v1` which is **in feature flags, but not in lib.rs** gen! macro. I can't import it like `use wayrs_protocols:input_method_unstable_v1`.

**Comment by MaxVerevkin** [comment]
Fixed in https://github.com/MaxVerevkin/wayrs/commit/329acecdbcf4404044f435be01f43b1b687d1f77

**Comment by MaxVerevkin** [comment]
And published a new version.
